name: Build Dylib
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
      - name: Build Package
        run: make package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FreeFire-Dylib
          path: .theos/obj/*.dylib
